name: CI

on: [ push, pull_request ]

jobs:
  build-linux:
    name: "Build - Linux"
    runs-on: ubuntu-latest
    container: wpilib/ubuntu-base:20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: Linux
          path: build/allOutputs

  build-windows:
    strategy:
      fail-fast: false
      matrix:
        include:
          - artifact-name: Win64
            architecture: x64
            vc: vcvars64.bat
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: ${{ matrix.architecture }}

      - uses: ilammy/setup-nasm@v1

      - name: Build with Gradle
        run: |
          @call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\${{ matrix.vc }}"
          gradlew build
        shell: cmd

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: build/allOutputs

  build-macos:
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14
    name: "Build - macOS"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: macOS
          path: build/allOutputs

  combine:
    name: Combine
    needs: [ build-linux, build-windows, build-macos ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: wpilibsuite/build-tools
      - uses: actions/download-artifact@v2
        with:
          path: combiner/products/build/allOutputs
      - name: Flatten Artifacts
        run: rsync -a --delete combiner/products/build/allOutputs/*/* combiner/products/build/allOutputs/
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Combine
        if: |
          !startsWith(github.ref, 'refs/tags/v')
        run: ./gradlew publish -Pthirdparty
        working-directory: combiner
      - name: Combine (Release)
        if: |
          github.repository_owner == 'wpilibsuite' &&
          startsWith(github.ref, 'refs/tags/v')
        run: |
          ./gradlew publish -Pthirdparty
        working-directory: combiner
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
          ARTIFACTORY_PUBLISH_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PUBLISH_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - uses: actions/upload-artifact@v2
        with:
          name: Maven
          path: ~/releases
